---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.externalSecrets.serviceAccount.name }}
  namespace: {{ .Values.externalSecrets.serviceAccount.namespace }}

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: supabase
spec:
  provider:
    aws:
      service: SecretsManager
      role: {{ .Values.externalSecrets.secretStore.roleArn }}
      region: {{ .Values.externalSecrets.secretStore.region }}
