---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: haproxy
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
    - name: studio
      port: 3000
      protocol: TCP
